dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - pytest tests/ch1
  - pytest tests/ch2
  - pytest tests/ch3/a
